version: "2.1"
services:
  provinces:
    image: provinces-app:latest
    ports:
      - "8988:9088"
  providers:
    image: providers-app:latest
    links:
      - provinces
  ha_providers:
    image: tutum/haproxy
    links:
      - providers
    ports:
      - "8987:9087"
#networks:
#  default:
#    external:
#      name: nat